export const sample_foods = [
  {
    id: "1",
    name: "Pizza Pepperoni",
    cookTime: "10-20",
    price: 110,
    stock: 10,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "2",
    name: "Meatball",
    price: 210,
    stock: 20,
    cookTime: "20-30",
    favorite: true,
    origins: ["persia", "middle east", "china"],
    stars: 5,
    imageUrl: "food-2.jpg",
    tags: ["SlowFood", "Lunch"],
  },
  {
    id: "3",
    name: "Hamburger",
    price: 98,
    stock: 5,
    cookTime: "10-15",
    favorite: false,
    origins: ["germany", "us"],
    stars: 3.5,
    imageUrl: "food-3.jpg",
    tags: ["FastFood", "Hamburger"],
  },
  {
    id: "4",
    name: "Fried Potatoes",
    price: 190,
    stock: 2,
    cookTime: "15-20",
    favorite: true,
    origins: ["belgium", "france"],
    stars: 3,
    imageUrl: "food-4.jpg",
    tags: ["FastFood", "Fry"],
  },
  {
    id: "5",
    name: "Chicken Soup",
    price: 110,
    stock: 11,
    cookTime: "40-50",
    favorite: false,
    origins: ["india", "asia"],
    stars: 3.5,
    imageUrl: "food-5.jpg",
    tags: ["SlowFood", "Soup"],
  },
  {
    id: "6",
    name: "Vegetables Pizza",
    price: 290,
    stock: 9,
    cookTime: "40-50",
    favorite: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "food-6.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "SlowFood", count: 2 },
  { name: "Hamburger", count: 1 },
  { name: "Fry", count: 1 },
  { name: "Soup", count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: "Ajay Yadav",
    email: "ajayretro1@gmail.com",
    password: "Ajay@123",
    address: "Gurgaon",
    isAdmin: true,
  },
  {
    id: 2,
    name: "Ajay Kumar",
    email: "ajaykumar@gmail.com",
    password: "ajaykumar@123",
    address: "Gurugram",
    isAdmin: false,
  },
  {
    id: 3,
    name: "SampleKing",
    email: "sampleKing@gmail.com",
    password: "sampleKing@123",
    address: "Sector 10A, Gurgaon, Haryana",
    isAdmin: true,
  },
];

export const sample_tickets = [
  {
    id: 1,
    code: "SAVE10",
    label: "Save 10 %",
    mark: 0.1,
    isActive: true,
  },
  {
    id: 2,
    code: "SAVE20",
    label: "Save 20 %",
    mark: 0.2,
    isActive: true,
  },
  {
    id: 3,
    code: "SAVE30",
    label: "Save 30 %",
    mark: 0.3,
    isActive: true,
  },
];
